### ISSUE TITLE
Feature: Redact with black square

### ISSUE THREAD

**Issue by malteos** [openredact/openredact-app#1]
Similar to "Suppression with X" => Redact with black, e.g., https://www.fileformat.info/info/unicode/char/25a0/index.htm

Integrate as an additional option in select-element

**Comment by langhabel** [comment]
I chose to make this part of the suppression configuration. Now, there is a little button in the field where the suppression character is entered, that sets the character to ▬. The sign ▬ turned out to be the only black one that doesn't have a significant margin left and right.
