### ISSUE TITLE
Backend crashes with unavailable recognizer

### ISSUE THREAD

**Issue by malteos** [openredact/openredact-app#18]
Error:
```
...
    return await dependant.call(**values)
  File "/Volumes/data/repo/schwaerzer/app/backend/app/endpoints.py", line 117, in find_piis
    recognizer_paths = [recognizer_name_to_path_lookup[name] for name in recognizers]
  File "/Volumes/data/repo/schwaerzer/app/backend/app/endpoints.py", line 117, in <listcomp>
    recognizer_paths = [recognizer_name_to_path_lookup[name] for name in recognizers]
KeyError: 'DePhoneNumberRecognizer'
```

Request:
```
Content-Disposition: form-data; name="recognizers"

["DePhoneNumberRecognizer","DeCountryRecognizer","EmailRecognizer","SpacyStatisticalRecognizer"]
```

Expected behavior:

- Do not crash. 
- Ignore missing recognizer, all other recognizer should be used, only trigger notification that the missing recoginzer was not included.

**Comment by langhabel** [comment]
The problem does only occur during development: We store previously entered config values for the anonymization and the activated recognizers in `window.localStorage`. In the latest version, the names/keys changed.

When ever such an error occurs you'll need to clear your local storage. In Chrome: Dev Tools > Application > Clear site data
