### ISSUE TITLE
Maltes ersten Eindrücke

### ISSUE THREAD

**Issue by malteos** [openredact/openredact-app#2]
- Überschriften für "Edit view" + "Preview redaction"
- Edit + Previews als Dokument hervorheben, nur den eigentlichen Inhalt in der weißen Box. Steuerelement (Buttons, ...) außerhalb. Vllt auch mehr Schatten + Kante (Wie in MS Word)
- "Download" button vllt oben
- Wording "Generalization,Suppression,.." unklar. Beispiele könnten helfen
- NER Types: Verschiedene Farben für verschiedene Typen
- Mouse-over tooltips für klickbare element (close etc)
- Zeilenumbrüche fehlen im Edit View (bei txt)

**Comment by langhabel** [comment]
- Überschriften für "Edit view" + "Preview redaction" -> möglicherweise erledigt sich das durch #3 und #13 
- Edit + Previews als Dokument hervorheben, nur den eigentlichen Inhalt in der weißen Box. Steuerelement (Buttons, ...) außerhalb. Vllt auch mehr Schatten + Kante (Wie in MS Word) -> ein Anfang in die Richtung sollte #13 machen
- "Download" button vllt oben -> #3 
- Wording "Generalization,Suppression,.." unklar. Beispiele könnten helfen -> #7 
- NER Types: Verschiedene Farben für verschiedene Typen -> #8
- Mouse-over tooltips für klickbare element (close etc) -> #14
- Zeilenumbrüche fehlen im Edit View (bei txt) -> a fix is in progress by @malteos
