### ISSUE TITLE
Loading the categories for manual annotation failed

### ISSUE THREAD

**Issue by odunayo12** [openredact/openredact-app#23]
Going through the frontend instructions, as itemized [here](https://github.com/openredact/openredact-app/blob/master/frontend/README.md#install-dependencies) but I keep getting the following `errors`:

1. Loading the categories for manual annotation failed.
2. Loading the list of available recognizers failed.

![image](https://user-images.githubusercontent.com/19196838/130943915-740e5e7c-47f1-4390-a8e3-3961b67dc506.png)
Furthermore, when one tries to upload a document one gets an `error` that reads: 

- Processing of your document failed
![image](https://user-images.githubusercontent.com/19196838/130944084-7098f9f8-9cde-4535-9dc1-6a416ec4b26c.png)

Any suggestion will do because there is no error for the warnings about `prefix-less CSS`, nothing else seems wrong going by the output of my `CLI`.

PS: The error was first detected by a friend and I reproduced same on my PC.

**Comment by Flow2908** [comment]
Hi, I am the mentioned fried in this post. Is there any update on that error? Can anyone confirm or refute?

**Comment by DieterSchmidt** [comment]
I am getting the same error.
I followed the README and did this:
```
# Clone the repo
git clone https://github.com/openredact/openredact-app.git
cd openredact-app

# Pull images & start containers
docker-compose pull
docker-compose up
```
The docker is starting but spits out the following error:
```
File "/app/app/endpoints.py", line 14, in <module>
backend_1   |     from anonymizer import AnonymizerConfig, Anonymizer, Pii, ParserError
backend_1   | ModuleNotFoundError: No module named 'anonymizer'
```
So it seems like there is something wrong with the python module `anonymizer`. I tried installing it manually, but:
```
$ pip install anonymizer
Requirement already satisfied: anonymizer in /home/{name}/.local/lib/python3.8/site-packages (0.0.6)
```
So I don't know why it can't be found.
I was able to open the frontend in my browser with `127.0.0.1:80`, but I got the above mentioned errors.

**Comment by langhabel** [comment]
Thank you very much for your bug reports 🙂

We updated the Docker images which should have fixed the issue.

Please rerun the following commands to test the latest version:
```
docker-compose pull
docker-compose up
```
